import os
import asyncio
import edge_tts
import requests
from pptx import Presentation
from pypdf import PdfReader

class NotebookEngine:
    def __init__(self, output_dir="./vault_output"):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def extract_text(self, pdf_path):
        reader = PdfReader(pdf_path)
        text = ""
        for page in reader.pages:
            if page.extract_text():
                text += page.extract_text() + "\n"
        return text

    def create_ppt(self, title, points, filename="summary_deck.pptx"):
        prs = Presentation()
        # Title slide
        slide = prs.slides.add_slide(prs.slide_layouts[0])
        slide.shapes.title.text = title
        slide.placeholders[1].text = "Generated by R.I.A.N. Notebook Engine"

        # Content slides
        for pt in points:
            slide = prs.slides.add_slide(prs.slide_layouts[1])
            slide.shapes.title.text = "Key Takeaway"
            slide.placeholders[1].text = pt
            
        path = os.path.join(self.output_dir, filename)
        prs.save(path)
        return path

    async def generate_audio_overview(self, text, filename="audio_overview.mp3"):
        voice = "en-US-AriaNeural"
        communicate = edge_tts.Communicate(text, voice)
        path = os.path.join(self.output_dir, filename)
        await communicate.save(path)
        return path

def sync_to_telegram(file_path, caption="R.I.A.N. Notebook Asset"):
    token = os.getenv("TELEGRAM_BOT_TOKEN")
    chat_id = os.getenv("TELEGRAM_CHAT_ID")
    if not token or not chat_id:
        print("Telegram credentials missing. Skipping cloud sync.")
        return False
    
    url = f"https://api.telegram.org/bot{token}/sendDocument"
    with open(file_path, "rb") as f:
        files = {"document": f}
        data = {"chat_id": chat_id, "caption": caption}
        response = requests.post(url, data=data, files=files)
    
    if response.status_code == 200:
        print(f"Successfully synced {file_path} to Telegram vault!")
        os.remove(file_path) # Delete local copy to keep zero server load
        return True
    else:
        print(f"Failed to sync: {response.text}")
        return False

print("NotebookEngine loaded successfully!")