import os
import asyncio
import edge_tts
from pptx import Presentation
from pypdf import PdfReader

class NotebookEngine:
    def __init__(self, output_dir="./vault_output"):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def extract_text(self, pdf_path):
        reader = PdfReader(pdf_path)
        text = ""
        for page in reader.pages:
            if page.extract_text():
                text += page.extract_text() + "\n"
        return text

    def create_ppt(self, title, points, filename="summary_deck.pptx"):
        prs = Presentation()
        # Title slide
        slide = prs.slides.add_slide(prs.slide_layouts[0])
        slide.shapes.title.text = title
        slide.placeholders[1].text = "Generated by R.I.A.N. Notebook Engine"

        # Content slides
        for pt in points:
            slide = prs.slides.add_slide(prs.slide_layouts[1])
            slide.shapes.title.text = "Key Takeaway"
            slide.placeholders[1].text = pt
            
        path = os.path.join(self.output_dir, filename)
        prs.save(path)
        return path

    async def generate_audio_overview(self, text, filename="audio_overview.mp3"):
        voice = "en-US-AriaNeural" # Natural sounding voice
        communicate = edge_tts.Communicate(text, voice)
        path = os.path.join(self.output_dir, filename)
        await communicate.save(path)
        return path

print("NotebookEngine initialized successfully!")
