import ast
import logging
from langchain_core.messages import HumanMessage, AIMessage

logger = logging.getLogger("rian.graph")

def code_verifier(state: dict):
    """
    Tester Agent: Analyzes the code generated by the Coder Agent.
    If it finds a syntax error, it sends a failure message back to fix it.
    If it passes, it approves it for the next stage (Human-in-the-loop).
    """
    messages = state.get("messages", [])
    if not messages:
        return {"messages": []}
        
    last_message = messages[-1].content
    
    # Check if the AI generated any Python code
    if "```python" in last_message:
        logger.info("Verifier Agent analyzing new skill code...")
        code_block = last_message.split("```python")[1].split("```")[0].strip()
        
        try:
            # Code ko compile karke check karna bina actually execute kiye
            ast.parse(code_block)
            logger.info("Verifier Agent: Syntax Check PASSED.")
            # Code sahi hai toh ek invisible approval message graph mein dal do
            return {"messages": [AIMessage(content="[SYSTEM VERIFIER]: Code syntax is perfect. Proceed to ask human for permission.")]}
            
        except SyntaxError as e:
            logger.error(f"Verifier Agent found a Syntax Error: {e}")
            # Galti milne par AI ko turant error bhej kar fix karne bolna
            error_msg = f"VERIFICATION FAILED: Found a SyntaxError at line {e.lineno} - {e.msg}. Please rewrite and fix the code."
            return {"messages": [HumanMessage(content=error_msg)]}
            
    return {"messages": []}